version: "3.1"

services:
  terraform-project-api:
    build:
      context: terraformProjectAPI/
    image: terraform-project-api
    environment:
      WORK_DIR: /project
      BIND_HOST: 0.0.0.0
      BIND_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./example-project:/project
